### ISSUE TITLE
Installation crashes Samsung Tab S 8.4 Lineage OS 17.1 (Android 10), what works and what doesn't

### ISSUE THREAD

**Issue by adrijanik** [feelfreelinux/octo4a#255]
Hi,
Thanks much for such a great project! Was hoping to get some tips on how to move forward with installation for samsung.

I'm trying to set up octo4a on an old Samsung Galaxy Tab S SM-T705 driven by LineageOS 17.1 (Android 10). Installation of 1.1.1 goes without failure on OnePlus Nord (Android 11) and I can control printer from the phone, but I can't use it as a target device for a long run I'd like to use a tablet instead. Below I list the problem and what I have tried, would appreciate if I can get some help.

**Version 1.1.1** crashes while installing -> there is a small message at the bottom: "Missing Storage Permission...", despite requested permissions being granted. Build takes few seconds and app stops, when re-open it is displayed as: Installation corrupted, reinstall the app, same problem persists.
**Versions < 1.1.1 and >= 1.0.0** installation jumps quickly to 150% and stops there.
below logs from version: 1.0.0:
```
💻 No bootstrap detected, proceeding with installation
💻 Downloading bootstrap [0.1.8](tel:0.1.8)
💻 Bootstrap extracted, setting it up...
🐸 [add-user.sh](http://add-user.sh/)
🐸 fake_proc_stat
🐸 [install-bootstrap.sh](http://install-bootstrap.sh/)
🐸 [ioctlHook.so](http://ioctlhook.so/)
🐸 root
🐸 root-pre5
🐸 [rootfs.tar.xz](http://rootfs.tar.xz/)
🐸 [run-bootstrap.sh](http://run-bootstrap.sh/)
🐸 bootstrap ready, run with [run-bootstrap.sh](http://run-bootstrap.sh/)
🐸 proot info: vpid 1: terminated with signal 11
🐸 proot info: vpid 1: terminated with signal 11
🐸 proot info: vpid 1: terminated with signal 11
🐸 proot info: vpid 1: terminated with signal 11
💻 Bootstrap installation done
💻 Bootstrap installed
🐸 proot info: vpid 1: terminated with signal 11
🐸 proot info: vpid 1: terminated with signal 11
🐸 proot info: vpid 1: terminated with signal 11
🐸 proot info: vpid 1: terminated with signal 11
💻 Dependencies installed
```
**Version 0.0.5** installs to some extant but starts infinitely (after half an hour still starting): "OctopPrint is starting... this should only take few seconds"

I tried to build a custom APK from Android Studio with some tweaks but so far no luck. Some finding: I got NullPointerException error (see below) which seems to be fixed with the addition of a conditional, this didn't help to run it but it builds and loads.
Android studio run with my device, log-level error
```
2022-08-03 22:23:39.035 24504-29191/com.octo4a E/ion: ioctl c0044901 failed with code -1: Invalid argument
2022-08-03 22:24:11.958 24504-24504/com.octo4a E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.octo4a, PID: 24504
    java.lang.NullPointerException: Attempt to get length of null array
        at com.octo4a.repository.ExtensionsRepositoryImpl.getValidExtensions(ExtensionsRepository.kt:213)
        at com.octo4a.ui.fragments.ExtensionsFragment.onViewCreated(ExtensionsFragment.kt:32)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2974)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:543)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2094)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
2022-08-03 22:26:02.429 30047-30047/? E/com.octo4a: Unknown bits set in runtime_flags: 0x8000
2022-08-03 22:26:12.064 30047-30138/com.octo4a E/ion: ioctl c0044901 failed with code -1: Invalid argument
```
Add condition if file exists (line 211):
<img width="748" alt="image" src="https://user-images.githubusercontent.com/21140501/182829881-6206c323-f164-47c9-b2fa-caf7dee15703.png">

I also tried to investigate "Missing storage permission message..." it lead me to [line 37 of InitialActivity](https://github.com/feelfreelinux/octo4a/blob/1.1.1/app/app/src/main/java/com/octo4a/ui/InitialActivity.kt#L37) where it checks if Write Permission was granted, in [here](https://github.com/feelfreelinux/octo4a/blob/1.1.1/app/app/src/main/java/com/octo4a/ui/InitialActivity.kt#L87) Toast display message after requesting permission. When adding post condition to check the permission it stil fails...
Not sure if it helps anyone, but would be grateful to get some ideas on how to make it work on Tab S 8.4.
Thanks!

**Comment by okeightysix** [comment]
`    private val hasStoragePermission: Boolean
        get() = ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED`

If this line requires "777" permission to write to external storage maybe it'll be the problem because when I tried to grant "777" on my rooted Mediapad T3 10 with root explorer it says access denied.
