### ISSUE TITLE
Upload failed - Could not upload the file

### ISSUE THREAD

**Issue by ZeleiAttila** [feelfreelinux/octo4a#34]
Hi,

I've installed the app on a Minix U9-H (Android 7.1.2). When I upload a gcode I get a error message: Upload failed. I've granted storage permission in application settings, but I can see in log there is a permission error. 
Can you help me? 

Thanks

system info:
>browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36
connectivity.connection_check: 1.1.1.1:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 8
env.hardware.freq: 1256
env.hardware.ram: 1755201536
env.os.bits: 64
env.os.id: linux
env.os.platform: linux
env.python.pip: 19.2.3
env.python.version: 3.8.0
env.python.virtualenv: false
octoprint.safe_mode: false
octoprint.version: 1.6.1
systeminfo.generator: systemapi

octoprint.log:

> 2021-09-14 22:21:02,430 - octoprint.startup - INFO - ******************************************************************************
2021-09-14 22:21:02,434 - octoprint.startup - INFO - Starting OctoPrint 1.6.1
2021-09-14 22:21:02,436 - octoprint.startup - INFO - ******************************************************************************
2021-09-14 22:21:02,462 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2021-09-14 22:21:02,463 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 1.1.1.1:53 is working
2021-09-14 22:21:02,463 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2021-09-14 22:21:02,565 - octoprint.plugin.core - INFO - Loading plugins from /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins, /data/data/com.octo4a/files/home/.octoprint/plugins and installed plugin packages...
2021-09-14 22:21:06,072 - octoprint.plugin.core - INFO - Plugin Pi Support Plugin (2021.8.2) did not pass check, not loading.
2021-09-14 22:21:06,376 - octoprint.plugin.core - INFO - Found 16 plugin(s) providing 16 mixin implementations, 32 hook handlers
2021-09-14 22:21:06,536 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2021-09-14 22:21:07,393 - octoprint.server - INFO - Intermediary server started
2021-09-14 22:21:07,402 - octoprint.printer.profile - ERROR - Profile _default does not exist, creating _default again and setting it as default
2021-09-14 22:21:07,633 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /storage/emulated/0/OctoPrint/uploads...
2021-09-14 22:21:07,637 - octoprint.filemanager.storage - INFO - ... file metadata for /storage/emulated/0/OctoPrint/uploads initialized successfully.
2021-09-14 22:21:07,645 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_SHOW (needs: "Need(method='role', value='plugin_action_command_notification_show')")
2021-09-14 22:21:07,646 - octoprint.server - INFO - Added new permission from plugin action_command_notification: PLUGIN_ACTION_COMMAND_NOTIFICATION_CLEAR (needs: "Need(method='role', value='plugin_action_command_notification_clear')")
2021-09-14 22:21:07,647 - octoprint.server - INFO - Added new permission from plugin action_command_prompt: PLUGIN_ACTION_COMMAND_PROMPT_INTERACT (needs: "Need(method='role', value='plugin_action_command_prompt_interact')")
2021-09-14 22:21:07,648 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_READ (needs: "Need(method='role', value='plugin_announcements_read')")
2021-09-14 22:21:07,650 - octoprint.server - INFO - Added new permission from plugin announcements: PLUGIN_ANNOUNCEMENTS_MANAGE (needs: "Need(method='role', value='plugin_announcements_manage'), Need(method='role', value='plugin_announcements_read')")
2021-09-14 22:21:07,652 - octoprint.server - INFO - Added new permission from plugin appkeys: PLUGIN_APPKEYS_ADMIN (needs: "Need(method='role', value='plugin_appkeys_admin')")
2021-09-14 22:21:07,655 - octoprint.server - INFO - Added new permission from plugin backup: PLUGIN_BACKUP_ACCESS (needs: "Need(method='role', value='plugin_backup_access')")
2021-09-14 22:21:07,658 - octoprint.server - INFO - Added new permission from plugin firmware_check: PLUGIN_FIRMWARE_CHECK_DISPLAY (needs: "Need(method='role', value='plugin_firmware_check_display')")
2021-09-14 22:21:07,660 - octoprint.server - INFO - Added new permission from plugin logging: PLUGIN_LOGGING_MANAGE (needs: "Need(method='role', value='plugin_logging_manage')")
2021-09-14 22:21:07,663 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_MANAGE (needs: "Need(method='role', value='plugin_pluginmanager_manage')")
2021-09-14 22:21:07,665 - octoprint.server - INFO - Added new permission from plugin pluginmanager: PLUGIN_PLUGINMANAGER_INSTALL (needs: "Need(method='role', value='plugin_pluginmanager_install'), Need(method='role', value='plugin_pluginmanager_manage')")
2021-09-14 22:21:07,668 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CHECK (needs: "Need(method='role', value='plugin_softwareupdate_check')")
2021-09-14 22:21:07,671 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_UPDATE (needs: "Need(method='role', value='plugin_softwareupdate_update')")
2021-09-14 22:21:07,673 - octoprint.server - INFO - Added new permission from plugin softwareupdate: PLUGIN_SOFTWAREUPDATE_CONFIGURE (needs: "Need(method='role', value='plugin_softwareupdate_configure')")
2021-09-14 22:21:10,907 - octoprint.util.pip - INFO - Using "/data/data/com.octo4a/files/usr/bin/python3 -m pip" as command to invoke pip
2021-09-14 22:21:14,021 - octoprint.util.pip - INFO - Version of pip is 19.2.3
2021-09-14 22:21:14,025 - octoprint.util.pip - INFO - pip installs to /data/data/com.octo4a/files/usr/lib/python3.8/site-packages (writable -> yes), --user flag needed -> no, virtual env -> no
2021-09-14 22:21:14,026 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-09-14 22:21:14,242 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2021-09-14 22:21:14,683 - octoprint.plugin.core - INFO - 16 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/errortracking
|  File Check (2021.2.23) (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint_file_check
|  Firmware Check (2021.8.11) (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint_firmware_check
|  GCode Viewer (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/gcodeviewer
|  Logging (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/logging
|  Plugin Manager (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/pluginmanager
|  Software Update (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2021-09-14 22:21:14,706 - octoprint.environment - INFO - Detected environment is Python 3.8.0 under Linux (linux). Details:
|  hardware:
|    cores: 8
|    freq: 1256.0
|    ram: 1755201536
|  os:
|    bits: 64
|    id: linux
|    platform: linux
|  python:
|    pip: 19.2.3
|    version: 3.8.0
2021-09-14 22:21:14,719 - octoprint.server - INFO - Reset webasset folder /data/data/com.octo4a/files/home/.octoprint/generated/webassets...
2021-09-14 22:21:14,722 - octoprint.server - INFO - Reset webasset folder /data/data/com.octo4a/files/home/.octoprint/generated/.webassets-cache...
2021-09-14 22:21:16,230 - octoprint.server - INFO - Shutting down intermediary server...
2021-09-14 22:21:16,254 - octoprint.server - INFO - Intermediary server shut down
2021-09-14 22:21:16,259 - octoprint.events - INFO - Processing startup event, this is our first event
2021-09-14 22:21:16,260 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2021-09-14 22:21:16,265 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2021-09-14 22:21:16,272 - octoprint.server.util.watchdog - INFO - Running initial scan on watched folder...
2021-09-14 22:21:16,276 - octoprint.server.util.watchdog - INFO - ... initial scan done.
2021-09-14 22:21:16,279 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2021-09-14 22:21:17,114 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on localhost._http._tcp.local.' for _http._tcp.local.
2021-09-14 22:21:18,111 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on localhost._octoprint._tcp.local.' for _octoprint._tcp.local.
2021-09-14 22:21:18,140 - octoprint.server - INFO - Listening on http://0.0.0.0:5000 and http://[::]:5000
2021-09-14 22:21:18,142 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on localhost for SSDP
2021-09-14 22:21:19,633 - octoprint.plugins.announcements - INFO - Loaded channel _important from https://octoprint.org/feeds/important.xml in 0.49s
2021-09-14 22:21:19,761 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from https://plugins.octoprint.org/plugins.json
2021-09-14 22:21:20,819 - octoprint.plugins.announcements - INFO - Loaded channel _releases from https://octoprint.org/feeds/releases.xml in 0.38s
2021-09-14 22:21:21,581 - octoprint.util.pip - INFO - Using "/data/data/com.octo4a/files/usr/bin/python3 -m pip" as command to invoke pip
2021-09-14 22:21:21,594 - octoprint.util.pip - INFO - pip installs to /data/data/com.octo4a/files/usr/lib/python3.8/site-packages (writable -> yes), --user flag needed -> no, virtual env -> no
2021-09-14 22:21:21,608 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-09-14 22:21:21,659 - octoprint.plugins.softwareupdate - INFO - Minimum free storage across all update relevant locations is 6.2GB. That is considered sufficient for updating.
2021-09-14 22:21:21,661 - octoprint.plugins.softwareupdate - INFO - Fetching check overlays from https://plugins.octoprint.org/update_check_overlay.json
2021-09-14 22:21:22,077 - octoprint.plugins.announcements - INFO - Loaded channel _blog from https://octoprint.org/feeds/octoblog.xml in 0.43s
2021-09-14 22:21:23,579 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from https://plugins.octoprint.org/feed.xml in 0.4s
2021-09-14 22:21:24,845 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from https://octoprint.org/feeds/octopi.xml in 0.32s
2021-09-14 22:21:25,177 - octoprint.plugins.pluginmanager - INFO - Loaded plugin notices data from https://plugins.octoprint.org/notices.json
2021-09-14 22:21:26,087 - octoprint.util.pip - INFO - Using "/data/data/com.octo4a/files/usr/bin/python3 -m pip" as command to invoke pip
2021-09-14 22:21:26,090 - octoprint.util.pip - INFO - pip installs to /data/data/com.octo4a/files/usr/lib/python3.8/site-packages (writable -> yes), --user flag needed -> no, virtual env -> no
2021-09-14 22:21:26,092 - octoprint.util.pip - INFO - ==> pip ok -> yes
2021-09-14 22:21:26,154 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2021-09-14 22:26:33,186 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.38
2021-09-14 22:26:34,818 - octoprint.server.util.flask.PreemptiveCache - INFO - Adding entry for / and {'path': '/', 'base_url': 'http://192.168.1.30:5000/', 'query_string': 'l10n=en', '_timestamp': 1631651194.818568, '_count': 1}
2021-09-14 22:26:50,087 - octoprint.server.util.sockjs - INFO - Client connection closed: 192.168.1.38
2021-09-14 22:26:51,784 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.38
2021-09-14 22:27:11,609 - octoprint.access.users - INFO - Logged in user: admin
2021-09-14 22:27:11,612 - octoprint.server.api - INFO - Actively logging in user admin from 192.168.1.38
2021-09-14 22:27:15,159 - octoprint.server.util.sockjs - INFO - User admin logged in on the socket from client 192.168.1.38
2021-09-14 22:27:26,054 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {'octoprint_uptime': 379, 'printer_state': 'OFFLINE'}
2021-09-14 22:27:26,409 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {'version': '1.6.1', 'os': 'linux', 'bits': 64, 'python': '3.8.0', 'pip': '19.2.3', 'cores': 8, 'freq': 1256.0, 'ram': 1755201536, 'plugins': ''}
2021-09-14 22:27:26,730 - octoprint.plugins.tracking - INFO - Sent tracking event startup, payload: {'version': '1.6.1', 'os': 'linux', 'bits': 64, 'python': '3.8.0', 'pip': '19.2.3', 'cores': 8, 'freq': 1256.0, 'ram': 1755201536}
2021-09-14 22:28:51,244 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Detecting serial connection"
2021-09-14 22:28:51,804 - octoprint.util.comm - INFO - Serial detection: Performing autodetection with 7 port/baudrate candidates: /data/data/com.octo4a/files/home/serialpipe@115200, /data/data/com.octo4a/files/home/serialpipe@250000, /data/data/com.octo4a/files/home/serialpipe@230400, /data/data/com.octo4a/files/home/serialpipe@57600, /data/data/com.octo4a/files/home/serialpipe@38400, /data/data/com.octo4a/files/home/serialpipe@19200, /data/data/com.octo4a/files/home/serialpipe@9600
2021-09-14 22:28:51,811 - octoprint.util.comm - INFO - Serial detection: Trying port /data/data/com.octo4a/files/home/serialpipe, baudrate 115200
2021-09-14 22:28:51,816 - octoprint.util.comm - INFO - Connecting to port /data/data/com.octo4a/files/home/serialpipe, baudrate 115200
2021-09-14 22:28:51,824 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #1 with timeout 2.0s
2021-09-14 22:28:51,829 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-09-14 22:28:55,802 - octoprint.util.comm - INFO - Serial detection: Handshake attempt #2 with timeout 2.0s
2021-09-14 22:28:55,822 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-09-14 22:28:55,845 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial connection" to "Operational"
2021-09-14 22:28:55,857 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2021-09-14 22:28:56,080 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin Marlin-JyersUI (Aug 10 2021 17:21:00)"
2021-09-14 22:28:56,134 - octoprint.util.comm - INFO - Firmware states that it supports temperature autoreporting
2021-09-14 22:28:56,205 - octoprint.util.comm - INFO - Firmware states that it supports emergency GCODEs to be sent without waiting for an acknowledgement first
2021-09-14 22:28:56,415 - octoprint.plugins.tracking - INFO - Sent tracking event printer_connected, payload: {'firmware_name': 'Marlin Marlin-JyersUI (Aug 10 2021 17:21:00)', 'printer_port': 'AUTO', 'printer_baudrate': 0}
2021-09-14 22:29:07,554 - octoprint - ERROR - Exception on /api/files/local [POST]
Traceback (most recent call last):
  File "/data/data/com.octo4a/files/usr/lib/python3.8/shutil.py", line 780, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Cross-device link: '/data/data/com.octo4a/files/usr/tmp/octoprint-file-upload-xs5noe7h.tmp' -> '/storage/emulated/0/OctoPrint/uploads/CE3_cableChain_link_v3_(1).gcode'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/server/util/flask.py", line 1550, in decorated_view
    return func(*args, **kwargs)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/vendor/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/server/api/files.py", line 641, in uploadGcodeFile
    added_file = fileManager.add_file(
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/filemanager/__init__.py", line 737, in add_file
    path_in_storage = self._storage(destination).add_file(
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/filemanager/storage.py", line 906, in add_file
    file_object.save(file_path)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/site-packages/octoprint/filemanager/util.py", line 69, in save
    shutil.move(self.path, path)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/shutil.py", line 794, in move
    copy_function(src, real_dst)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/shutil.py", line 427, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/data/data/com.octo4a/files/usr/lib/python3.8/shutil.py", line 366, in copystat
    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),
PermissionError: [Errno 1] Operation not permitted

**Comment by th3Shah** [comment]
I have the same error but I upload to sd card and then refresh the sd card and the file appears. Mabe after an upload a wait time and then auto-refreshing the storage might help.

**Comment by ZeleiAttila** [comment]
Hi,

I try the new release, but I got error when install, then I see "Installation corrupted" message in application.

Log:
💻 No bootstrap detected, proceeding with installation
💻 Downloading bootstrap 0.1.6
💻 Bootstrap extracted, setting it up...
🐸 add-user.sh
🐸 fake_proc_stat
🐸 install-bootstrap.sh
🐸 ioctlHook.so
🐸 root
🐸 rootfs.tar.xz
🐸 run-bootstrap.sh
🐸 install-bootstrap.sh[6]: ../root/bin/minitar: can't execute: Permission denied
🐸 install-bootstrap.sh[11]: can't create bootstrap/etc/resolv.conf: No such file or directory
🐸 bootstrap ready, run with run-bootstrap.sh
🐸 add-user.sh[5]: can't create bootstrap/etc/passwd: No such file or directory
🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied
🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied
🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied
🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied
💻 Bootstrap installation done
💻 Bootstrap installed
🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied
🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied
🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied
🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied
💻 Dependencies installed

**Comment by feelfreelinux** [comment]
> Hi,
> 
> I try the new release, but I got error when install, then I see "Installation corrupted" message in application.
> 
> Log: 💻 No bootstrap detected, proceeding with installation 💻 Downloading bootstrap 0.1.6 💻 Bootstrap extracted, setting it up... 🐸 add-user.sh 🐸 fake_proc_stat 🐸 install-bootstrap.sh 🐸 ioctlHook.so 🐸 root 🐸 rootfs.tar.xz 🐸 run-bootstrap.sh 🐸 install-bootstrap.sh[6]: ../root/bin/minitar: can't execute: Permission denied 🐸 install-bootstrap.sh[11]: can't create bootstrap/etc/resolv.conf: No such file or directory 🐸 bootstrap ready, run with run-bootstrap.sh 🐸 add-user.sh[5]: can't create bootstrap/etc/passwd: No such file or directory 🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied 🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied 🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied 🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied 💻 Bootstrap installation done 💻 Bootstrap installed 🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied 🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied 🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied 🐸 run-bootstrap.sh[36]: ./root/bin/proot: can't execute: Permission denied 💻 Dependencies installed

Please try to do a fresh install, it should work now :) 

(Fixed in https://github.com/feelfreelinux/android-linux-bootstrap 0.1.8)

**Comment by ZeleiAttila** [comment]
Hi,

Thank you. Everything works fine. The original issue was solved too.
