### ISSUE TITLE
Proot warning: can't sanitize binding "/data/data" willing to pay for a fix

### ISSUE THREAD

**Issue by koruptdata** [feelfreelinux/octo4a#479]
I've been searching and searching for a fix for octo4a failing to install, I found many people reporting the same problem in the past. But the only "fix" was just using a VPN.. I tried that with no luck

I used to have octo4a running version 1.2.5 on my phone and it worked flawlessly, I uninstalled it to update to the recently released 1.2.6 but it fails to install every time. No big deal I thought, I can just go back and use what worked before... Now 1.2.5 won't reinstall and fails with the same error. I'm willing to pay anyone who can help me figure out how to at least get 1.2.5 back up and running.

An exception has occurred at:
java.lang.RuntimeException: Process exited with error code 1. [proot warning: can't sanitize binding "/data/data
at com.octo4a.utils.ProcessUtilsKt.waitAndPrintOutput(ProcessUtils.kt:43)
at com.octo4a.utils.ProcessUtilsKt.waitAndPrintOutput$default(ProcessUtils.kt:16)
at com.octo4a.repository.OctoPrintHandlerRepositoryImpl$beginInstallation$2.invokeSuspend(OctoPrintHandlerRepository.kt:168)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Builders.common.kt:265)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Exception:
java.lang.RuntimeException: Process exited with error code 1. [proot warning: can't sanitize binding "/data/data

**Comment by feelfreelinux** [comment]
Hi, sorry for the broken hot fix. Seems like 1.2.6 only resolved the issue on some devices. I'll try to have an update ready this week, and will add in an option to install a legacy octoprint version as a part of it - to keep such issues from completely breaking setups in the future.

**Comment by koruptdata** [comment]
> Hi, sorry for the broken hot fix. Seems like 1.2.6 only resolved the issue on some devices. I'll try to have an update ready this week, and will add in an option to install a legacy octoprint version as a part of it - to keep such issues from completely breaking setups in the future.

No problem, I'm just happy that you made such an amazing app for us to use in the first place, I'll be sure to send some money over to your paypal!

**Comment by MrX999** [comment]
Hi. Is there any update on how to download octo4a? I'm getting the same error on both devices. This is my first time trying to use octo4a. Also tried few older versions including 1.2.5 but all fail when trying to install. Think it always tries to download newest version even when you select an older version. Any ideas. Thanks for your help

**Comment by Adithr123** [comment]
Wait for the next update/hotfix.

**Comment by Adithr123** [comment]
> Hi, sorry for the broken hot fix. Seems like 1.2.6 only resolved the issue on some devices. I'll try to have an update ready this week, and will add in an option to install a legacy octoprint version as a part of it - to keep such issues from completely breaking setups in the future.

Any updates?

**Comment by feelfreelinux** [comment]
> > Hi, sorry for the broken hot fix. Seems like 1.2.6 only resolved the issue on some devices. I'll try to have an update ready this week, and will add in an option to install a legacy octoprint version as a part of it - to keep such issues from completely breaking setups in the future.
> 
> 
> 
> Any updates?

Almost finished the update - need a bit more time to test out and make sure that it works fine :) In the meantime, feel free to use this workaround 

https://github.com/feelfreelinux/octo4a/issues/483

**Comment by Adithr123** [comment]
> > > Hi, sorry for the broken hot fix. Seems like 1.2.6 only resolved the issue on some devices. I'll try to have an update ready this week, and will add in an option to install a legacy octoprint version as a part of it - to keep such issues from completely breaking setups in the future.
> > 
> > 
> > Any updates?
> 
> Almost finished the update - need a bit more time to test out and make sure that it works fine :) In the meantime, feel free to use this workaround
> 
> #483

Im not able to ssh in, it just refuses to connect.

**Comment by kekkodance** [comment]
Tried the workaround, it did nothing

**Comment by MrX999** [comment]
> > > Hi, sorry for the broken hot fix. Seems like 1.2.6 only resolved the issue on some devices. I'll try to have an update ready this week, and will add in an option to install a legacy octoprint version as a part of it - to keep such issues from completely breaking setups in the future.
> > 
> > 
> > Any updates?
> 
> Almost finished the update - need a bit more time to test out and make sure that it works fine :) In the meantime, feel free to use this workaround
> 
> #483

Let us know when testing complete. Thanks for all your help.

**Comment by MrX999** [comment]
Let us know when testing is completed. Thanks for all your help

**Comment by feelfreelinux** [comment]
Released https://github.com/feelfreelinux/octo4a/releases/tag/2.0.0 which should resolve this issue :)
