### ISSUE TITLE
octoklipper error: externally-managed-environment

### ISSUE THREAD

**Issue by zaid-hm** [feelfreelinux/octo4a#493]
I'm trying to run klipper on a galaxy tab A (2019)
But when running the command in the instruction I get the following error:
```

bash -c "$(curl -fsSL https://raw.githubusercontent.com/feelfreelinux/octo4a/master/scrip
ts/setup-klipper.sh)"
Setting up klipper
Do you have "Plugin extras" installed? (y/n): y
Installing dependencies...

OK: 404 MiB in 183 packages
error: externally-managed-environment

× This environment is externally managed
╰─>
    The system-wide python installation should be maintained using the system
    package manager (apk) only.

    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:

    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage

    To exit the virtual environment, run:

    deactivate

    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.

    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
localhost:~# bash -c "$(curl -fsSL https://raw.githubusercontent.com/feelfreelinux/octo4a/master/scrip
ts/setup-klipper.sh)"
```

**Comment by Bartouzz** [comment]
There is a new script for the 2.0.0 version of octo4a

https://github.com/feelfreelinux/octo4a/blob/master/scripts/setup-klipper-moonraker.sh

By the way i'm still figuring out, how to get it to work i'm running network error.
Maybe you should install 1.2.6 version of octo4a and use the command line you did.

**Comment by zaid-hm** [comment]
@Bartouzz did you manage to get it to work, I'm running into a network issue as well

**Comment by Bartouzz** [comment]
@zaid-hm Still not ... Starting to lose hope, see my current klippy log:

mcu 'mcu': Starting serial connect
mcu 'mcu': Unable to open serial port: [Errno 13] Could not exclusively lock port /dev/ttyOcto4a: [Errno 13] Permission denied
webhooks client 489798200720: New connection
webhooks client 489798200720: Client info {'program': 'Moonraker', 'version': 'v0.8.0-384-g8f3b30a'}
mcu 'mcu': Unable to open serial port: [Errno 13] Could not exclusively lock port /dev/ttyOcto4a: [Errno 13] Permission denied

seem's like permission problem but i can't find the right answer. i'll post if get something

**Comment by schmttc** [comment]
Try using this install script, it ignores the 'externally managed' error:
https://raw.githubusercontent.com/schmttc/octo4a/fixklipperinstall/scripts/setup-klipper.sh

**Comment by schmttc** [comment]
I'm working on this issue, am updating the klipper install script to work with octo4a 2.0
Once I've done some testing will provide the details for you to confirm.

**Comment by schmttc** [comment]
I've fixed the environment and permission denied error, but have run into the next error (non rooted device) https://github.com/schmttc/octo4a/blob/schmttc-patch-1/scripts/setup-klipper.sh
Have confirmed that Klipper on a Raspberry Pi 3B is working with the printer.

```
mcu 'mcu': Wait for identify_response
Traceback (most recent call last):
  File "/klipper/klippy/serialhdl.py", line 68, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/klipper/klippy/serialhdl.py", line 262, in send_with_response
    return src.get_response([cmd], self.default_cmd_queue)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/klipper/klippy/serialhdl.py", line 319, in get_response
    self.serial.raw_send_wait_ack(cmds[-1], minclock, reqclock,
  File "/klipper/klippy/serialhdl.py", line 254, in raw_send_wait_ack
    self._error("Serial connection closed")
  File "/klipper/klippy/serialhdl.py", line 61, in _error
    raise error(self.warn_prefix + (msg % params))
serialhdl.error: mcu 'mcu': Serial connection closed
```

**Comment by schmttc** [comment]
I've used setup-klipper-moonraker.sh and reduced it to only install Klipper, which resolves all issues.

Please try https://github.com/schmttc/octo4a/blob/klipper-fix/scripts/setup-klipper.sh

Note, you will get this error in klippy.log if Klipper is not set to the correct serial port, or the printer is not available/powered off. This error will go away once the printer is connected and configured correctly.
```
mcu 'mcu': Starting serial connect
mcu 'mcu': Timeout on connect
mcu 'mcu': Wait for identify_response
Traceback (most recent call last):
  File "/root/klipper/klippy/serialhdl.py", line 68, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/klipper/klippy/serialhdl.py", line 262, in send_with_response
    return src.get_response([cmd], self.default_cmd_queue)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/klipper/klippy/serialhdl.py", line 319, in get_response
    self.serial.raw_send_wait_ack(cmds[-1], minclock, reqclock,
  File "/root/klipper/klippy/serialhdl.py", line 254, in raw_send_wait_ack
    self._error("Serial connection closed")
  File "/root/klipper/klippy/serialhdl.py", line 61, in _error
    raise error(self.warn_prefix + (msg % params))
serialhdl.error: mcu 'mcu': Serial connection closed
```

**Comment by schmttc** [comment]
This may need more troubleshooting, while everything kicked off OK either Octoprint or Klipper crashed part way though a test print

**Comment by apparle** [comment]
I'm trying to use [setup-klipper-moonraker.sh](https://github.com/feelfreelinux/octo4a/blob/master/scripts/setup-klipper-moonraker.sh) itself and faced similar `Permission denied` errors.
Based on your pull request, I added `LD_PRELOAD=/home/octoprint/ioctl-hook.so` while launching klippy.py and now I'm getting errors similar to you. @schmttc how did you solve those errors?
```
mcu 'mcu': Wait for identify_response
```

What is connection information in your printer.cfg? Mine is:
```
[mcu]
serial: /dev/ttyOcto4a
baud: 250000
restart_method: command
```
Also, I checked that my printer is setup correctly because other devices running Klippy are able to control it. 
And FWIW, I'm running Octo4a on a non-rooted Android 11 device -- and that device could control a Marlin-firmware-printer correctly without the extension.

**Comment by schmttc** [comment]
> I'm trying to use [setup-klipper-moonraker.sh](https://github.com/feelfreelinux/octo4a/blob/master/scripts/setup-klipper-moonraker.sh) itself and faced similar `Permission denied` errors. Based on your pull request, I added `LD_PRELOAD=/home/octoprint/ioctl-hook.so` while launching klippy.py and now I'm getting errors similar to you. @schmttc how did you solve those errors?
> 
> ```
> mcu 'mcu': Wait for identify_response
> ```
> 
> What is connection information in your printer.cfg? Mine is:
> 
> ```
> [mcu]
> serial: /dev/ttyOcto4a
> baud: 250000
> restart_method: command
> ```
> 
> Also, I checked that my printer is setup correctly because other devices running Klippy are able to control it. And FWIW, I'm running Octo4a on a non-rooted Android 11 device -- and that device could control a Marlin-firmware-printer correctly without the extension.

Sadly I never got to the bottom of this, it worked intermittently a couple of times and then not again. 
Same issue on unrooted Android 11 and 13.
Connection works when connecting to a Raspberry Pi 3
MCU config
```
[mcu]
serial: /dev/ttyOcto4a
restart_method: command
```
Error
```
mcu 'mcu': Wait for identify_response
Traceback (most recent call last):
  File "/root/klipper/klippy/serialhdl.py", line 68, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/klipper/klippy/serialhdl.py", line 262, in send_with_response
    return src.get_response([cmd], self.default_cmd_queue)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/klipper/klippy/serialhdl.py", line 319, in get_response
    self.serial.raw_send_wait_ack(cmds[-1], minclock, reqclock,
  File "/root/klipper/klippy/serialhdl.py", line 254, in raw_send_wait_ack
    self._error("Serial connection closed")
  File "/root/klipper/klippy/serialhdl.py", line 61, in _error
    raise error(self.warn_prefix + (msg % params))
serialhdl.error: mcu 'mcu': Serial connection closed
```

**Comment by schmttc** [comment]
@apparle I've done some testing, and if you use the older Octo4a app version 1.2.6, it installs the latest Octoprint, and fixes the Klipper issues

**Comment by spenc302** [comment]
Find a fix or at least a cause? Tried to roll back to older version of octo4a and it's still giving me permission errors, would a work around be using a rooted device

**Comment by akei-ai** [comment]
Hello, I got it to work on the main version of Octo4a. The changes I have done is on /mnt/.../klipper/start.sh and adding LD_PRELOAD=/home/octoprint/...

Version: Android 13 (NOT ROOTED)
Device: Asus Zenfone Max Pro M1


Printing is working. I am printing a benchy right now
Edited Files:
/mnt/external/extensions/klipper/start.sh
```
#!/bin/sh

KLIPPER_ARGS="/root/klipper/klippy/klippy.py /root/printer.cfg -l /root/printer_data/logs/klippy.log -I /root/printer_data/comms/klippy.serial -a >
/root/klipper-venv/bin/python \$KLIPPER_ARGS &
MOONRAKER_ARGS="/root/moonraker/moonraker/moonraker.py -d /root/printer_data"

nginx
LD_PRELOAD=/home/octoprint/ioctl-hook.so /root/klipper-venv/bin/python $KLIPPER_ARGS &
LD_PRELOAD=/home/octoprint/ioctl-hook.so /root/moonraker-venv/bin/python $MOONRAKER_ARGS

```
~/printer_data/config/printer.cfg
```
#include mainsail.cfg. Adding the path on printer.cfg for some reasons on my setup breaks moonraker.
[include mainsail.cfg]
...
```
~/printer_data/config/mainsail.cfg
```
[virtual_sdcard]
path: ~/printer_data/gcodes
```

**Comment by akei-ai** [comment]
> Hello, I got it to work on the main version of Octo4a. The changes I have done is on /mnt/.../klipper/start.sh and adding LD_PRELOAD=/home/octoprint/...
> 
> Version: Android 13 (NOT ROOTED) Device: Asus Zenfone Max Pro M1
> 
> Printing is working. I am printing a benchy right now Edited Files: /mnt/external/extensions/klipper/start.sh
> 
> ```
> #!/bin/sh
> 
> KLIPPER_ARGS="/root/klipper/klippy/klippy.py /root/printer.cfg -l /root/printer_data/logs/klippy.log -I /root/printer_data/comms/klippy.serial -a >
> /root/klipper-venv/bin/python \$KLIPPER_ARGS &
> MOONRAKER_ARGS="/root/moonraker/moonraker/moonraker.py -d /root/printer_data"
> 
> nginx
> LD_PRELOAD=/home/octoprint/ioctl-hook.so /root/klipper-venv/bin/python $KLIPPER_ARGS &
> LD_PRELOAD=/home/octoprint/ioctl-hook.so /root/moonraker-venv/bin/python $MOONRAKER_ARGS
> ```
> 
> ~/printer_data/config/printer.cfg
> 
> ```
> #include mainsail.cfg. Adding the path on printer.cfg for some reasons on my setup breaks moonraker.
> [include mainsail.cfg]
> ...
> ```
> 
> ~/printer_data/config/mainsail.cfg
> 
> ```
> [virtual_sdcard]
> path: ~/printer_data/gcodes
> ```

![Screenshot_20241027_030601](https://github.com/user-attachments/assets/95d79200-a425-40c9-8be0-b87a9ff6b33f)
![Screenshot_20241027_030512](https://github.com/user-attachments/assets/4d50f7f9-0914-4874-8c09-a6dc1c14aa74)

**Comment by apparle** [comment]
@akei-ai can you report which version of the https://github.com/feelfreelinux/octo4a-bootstrap-builder (selected first time octo4a sets up the octoprint server) you got working with Klipper?.
Based on my conversation with @feelfreelinux, he had fixed the ioctl issue in https://github.com/feelfreelinux/octo4a-bootstrap-builder/commit/364ee8b282b7f751bd8fa3b84a46bce6fbe6aaf4 such that klipper can open the device, and I was going to test that fix. But for other reasons, I had to rollback to Marlin firmware on my printer and never got around to testing it.

**Comment by akei-ai** [comment]
@apparle I got the 2.1.0 version, and the current Octoprint builder 1.10.2-f4f81ac1?

I've gotten it to work on two devices: I haven't tested other devices besides this.
Huawei Y7 (Android 7)
Asus Zenfone Max Pro M1 (Pixel Experience Custom Rom, Android 13)

I think its pretty much in an alpha state right now, Octo4a crashes sometimes when using the klipper+mainsail+moonraker setup but it works pretty much that I'm printing

**Comment by apparle** [comment]
I tried with a latest build of the builder that includes the fix. And I also did the changes to include LD_PRELOAD, but I still can't get it to work :-( 
Still plagued with `Serial connection closed` errors. And I tried with Android 9 (lineage OS) and Android 11 (e/OS/).

@akei-ai did you use a rooted device? Mine isn't rooted, and I wonder if that's the big difference.

**Comment by that-ambuj** [comment]
@apparle Octo4a doesn't require root and nor does it ask for it even if your device is rooted.

Not using root is one of its drawbacks. If you want some advice from me, just root that phone, use linux deploy for klipper and point mainsail to webcam(localhost:some port) url for Octo4a. Worked pretty well for me, you'll find plenty of guides online as well, except for the webcam part.

**Comment by apparle** [comment]
> [@apparle](https://github.com/apparle) Octo4a doesn't require root and nor does it ask for it even if your device is rooted.
> 
> Not using root is one of its drawbacks. If you want some advice from me, just root that phone, use linux deploy for klipper and point mainsail to webcam(localhost:some port) url for Octo4a. Worked pretty well for me, you'll find plenty of guides online as well, except for the webcam part.

I did try that route but it's harder than it looks.
1st Linux Deploy is broken Android 10 onwards, so I've to downgrade to Android 9. 
2nd, the linux deploy debian images use Debian10 which is super old and doesn't have some packages like newer version of Python, which are required by KIAUH scriptware, so that has to be compiled from scratch. 
3rd, my phone's kernel lacks the CH34x driver needed for USB-to-serial on my printer, so debian doesn't have a way to connect to the usb port. Instead I've to rely on the octo4a's userspace usb-to-serial driver by actually starting octo4a server and then symlinking the userspace serialport file into my debian session and using that.
And for whatever weird reason, I see that if my phone stays locked, the whole thing slows down -- and none of the power settings I could find I solve this throttling. 

The whole setup is extremely janky, so I'm looking for a simpler fix (like octo4a's serial driver to just work).

**Comment by akei-ai** [comment]
> I tried with a latest build of the builder that includes the fix. And I also did the changes to include LD_PRELOAD, but I still can't get it to work :-( Still plagued with `Serial connection closed` errors. And I tried with Android 9 (lineage OS) and Android 11 (e/OS/).
> 
> [@akei-ai](https://github.com/akei-ai) did you use a rooted device? Mine isn't rooted, and I wonder if that's the big difference.

no, not really. The device I use klipper with, for over a few months now doesn't have root. One note however, I think when klipper restarts sometimes, Android seems to fail to recognize and give control of the USB device to octo4a. Replugging the OTG seems to fix it.
