### ISSUE TITLE
Crash details Invalid version string [unknown]

### ISSUE THREAD

**Issue by techker** [feelfreelinux/octo4a#9]
Got a crash at continue when install is done:

debug info :
Added Timber Lib and traced : DBG info on App version unknown and new release 0.0.5
Android 10 samsung SM-G965W

once code was commented app works.
commented in checkUpdateAvailable()

                   if (SemVer.parse(version) < SemVer.parse(newestRelease.tagName)) {
                       // New version available, check if is built already
                      if (newestRelease.assets.any { it.name.contains("bootstrap") }
                         && newestRelease.assets.any { it.name.contains(".apk") }) {
                          updateAvailable.postValue(newestRelease)                       }
                   }

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.octo4a, PID: 27893
    java.lang.IllegalArgumentException: Invalid version string [unknown]
        at com.octo4a.utils.SemVer$Companion.parse(SemVer.kt:30)
        at com.octo4a.viewmodel.StatusViewModel$checkUpdateAvailable$1$1.invokeSuspend(StatusViewModel.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by feelfreelinux** [comment]
Can't reproduce in 1.0.0+, probably old issue. Feel free to reopen if you still experience this
