### ISSUE TITLE
Fails to start on device android 4.4.2 without camera 

### ISSUE THREAD

**Issue by white777777** [feelfreelinux/octo4a#97]
I have old device with android 4.4.2 without camera. Formely it is dlp projector with android. I've installed octo4a but it fails on start. 
There are some logcat logs.
```
W/dalvikvm( 7455): VFY: unable to resolve virtual method 19379: Landroidx/core/app/ComponentActivity;.onRequestPermissionsResult (I[Ljava/lang/String;[I)V
W/dalvikvm( 7455): VFY: unable to resolve static method 1864: Landroid/os/Handler;.createAsync (Landroid/os/Looper;)Landroid/os/Handler;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 609: Landroid/content/Context;.getSystemService (Ljava/lang/Class;)Ljava/lang/Object;
W/dalvikvm( 7455): VFY: unable to resolve interface method 3311: Landroid/view/Window$Callback;.onPointerCaptureChanged (Z)V
W/dalvikvm( 7455): VFY: unable to resolve interface method 3313: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
W/dalvikvm( 7455): VFY: unable to resolve interface method 3315: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
W/dalvikvm( 7455): VFY: unable to resolve interface method 3319: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 867: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 890: Landroid/content/res/TypedArray;.getType (I)I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 579: Landroid/content/Context;.createDeviceProtectedStorageContext ()Landroid/content/Context;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 586: Landroid/content/Context;.getCodeCacheDir ()Ljava/io/File;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 587: Landroid/content/Context;.getColor (I)I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 588: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 590: Landroid/content/Context;.getDataDir ()Ljava/io/File;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 591: Landroid/content/Context;.getDrawable (I)Landroid/graphics/drawable/Drawable;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 598: Landroid/content/Context;.getMainExecutor ()Ljava/util/concurrent/Executor;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 600: Landroid/content/Context;.getNoBackupFilesDir ()Ljava/io/File;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 609: Landroid/content/Context;.getSystemService (Ljava/lang/Class;)Ljava/lang/Object;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 611: Landroid/content/Context;.getSystemServiceName (Ljava/lang/Class;)Ljava/lang/String;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 614: Landroid/content/Context;.isDeviceProtectedStorage ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 631: Landroid/content/Context;.startForegroundService (Landroid/content/Intent;)Landroid/content/ComponentName;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2768: Landroid/view/View;.addKeyboardNavigationClusters (Ljava/util/Collection;I)V
W/dalvikvm( 7455): Link of class 'Landroidx/core/view/ViewCompat$2;' failed
E/dalvikvm( 7455): Could not find class 'androidx.core.view.ViewCompat$2', referenced from method androidx.core.view.ViewCompat.addOnUnhandledKeyEventListener
W/dalvikvm( 7455): VFY: unable to resolve new-instance 3131 (Landroidx/core/view/ViewCompat$2;) in Landroidx/core/view/ViewCompat;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2777: Landroid/view/View;.cancelDragAndDrop ()V
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/WindowInsets;)
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2785: Landroid/view/View;.dispatchApplyWindowInsets (Landroid/view/WindowInsets;)Landroid/view/WindowInsets;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2791: Landroid/view/View;.dispatchNestedFling (FFZ)Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2792: Landroid/view/View;.dispatchNestedPreFling (FF)Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2793: Landroid/view/View;.dispatchNestedPreScroll (II[I[I)Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2794: Landroid/view/View;.dispatchNestedScroll (IIII[I)Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2813: Landroid/view/View;.getBackgroundTintList ()Landroid/content/res/ColorStateList;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2814: Landroid/view/View;.getBackgroundTintMode ()Landroid/graphics/PorterDuff$Mode;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2823: Landroid/view/View;.getElevation ()F
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2830: Landroid/view/View;.getImportantForAutofill ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2848: Landroid/view/View;.getNextClusterForwardId ()I
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/WindowInsets;)
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/WindowInsets;)
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2870: Landroid/view/View;.getScrollIndicators ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2873: Landroid/view/View;.getSystemGestureExclusionRects ()Ljava/util/List;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2879: Landroid/view/View;.getTransitionName ()Ljava/lang/String;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2882: Landroid/view/View;.getTranslationZ ()F
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2893: Landroid/view/View;.getZ ()F
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2894: Landroid/view/View;.hasExplicitFocusable ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2897: Landroid/view/View;.hasNestedScrollingParent ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2909: Landroid/view/View;.isFocusedByDefault ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2911: Landroid/view/View;.isImportantForAutofill ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2914: Landroid/view/View;.isKeyboardNavigationCluster ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2919: Landroid/view/View;.isNestedScrollingEnabled ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2927: Landroid/view/View;.keyboardNavigationClusterSearch (Landroid/view/View;I)Landroid/view/View;
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/WindowInsets;)
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2932: Landroid/view/View;.onApplyWindowInsets (Landroid/view/WindowInsets;)Landroid/view/WindowInsets;
E/dalvikvm( 7455): Could not find class 'android.view.View$OnUnhandledKeyEventListener', referenced from method androidx.core.view.ViewCompat.removeOnUnhandledKeyEventListener
W/dalvikvm( 7455): VFY: unable to resolve check-cast 577 (Landroid/view/View$OnUnhandledKeyEventListener;) in Landroidx/core/view/ViewCompat;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2965: Landroid/view/View;.requestApplyInsets ()V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2971: Landroid/view/View;.requireViewById (I)Landroid/view/View;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2973: Landroid/view/View;.restoreDefaultFocus ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2986: Landroid/view/View;.setAutofillHints ([Ljava/lang/String;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2990: Landroid/view/View;.setBackgroundTintList (Landroid/content/res/ColorStateList;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2991: Landroid/view/View;.setBackgroundTintMode (Landroid/graphics/PorterDuff$Mode;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2995: Landroid/view/View;.setElevation (F)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 2999: Landroid/view/View;.setFocusedByDefault (Z)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3003: Landroid/view/View;.setImportantForAutofill (I)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3004: Landroid/view/View;.setKeyboardNavigationCluster (Z)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3014: Landroid/view/View;.setNestedScrollingEnabled (Z)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3015: Landroid/view/View;.setNextClusterForwardId (I)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3016: Landroid/view/View;.setOnApplyWindowInsetsListener (Landroid/view/View$OnApplyWindowInsetsListener;)V
W/dalvikvm( 7455): Link of class 'Landroidx/core/view/ViewCompat$1;' failed
E/dalvikvm( 7455): Could not find class 'androidx.core.view.ViewCompat$1', referenced from method androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener
W/dalvikvm( 7455): VFY: unable to resolve new-instance 3130 (Landroidx/core/view/ViewCompat$1;) in Landroidx/core/view/ViewCompat;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3029: Landroid/view/View;.setPointerIcon (Landroid/view/PointerIcon;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3038: Landroid/view/View;.setScrollIndicators (I)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3039: Landroid/view/View;.setScrollIndicators (II)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3044: Landroid/view/View;.setSystemGestureExclusionRects (Ljava/util/List;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3048: Landroid/view/View;.setTooltipText (Ljava/lang/CharSequence;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3050: Landroid/view/View;.setTransitionName (Ljava/lang/String;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3054: Landroid/view/View;.setTranslationZ (F)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3059: Landroid/view/View;.setZ (F)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3062: Landroid/view/View;.startDragAndDrop (Landroid/content/ClipData;Landroid/view/View$DragShadowBuilder;Ljava/lang/Object;I)Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3063: Landroid/view/View;.startNestedScroll (I)Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3064: Landroid/view/View;.stopNestedScroll ()V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3067: Landroid/view/View;.updateDragShadow (Landroid/view/View$DragShadowBuilder;)V
W/dalvikvm( 7455): Link of class 'Landroidx/core/view/ViewCompat$2;' failed
W/dalvikvm( 7455): Link of class 'Landroidx/core/view/ViewCompat$1;' failed
W/dalvikvm( 7455): VFY: unable to resolve direct method 3104: Landroid/view/ViewGroup;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 830: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 832: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
E/dalvikvm( 7455): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method androidx.appcompat.widget.AppCompatImageHelper.hasOverlappingRendering
W/dalvikvm( 7455): VFY: unable to resolve instanceof 236 (Landroid/graphics/drawable/RippleDrawable;) in Landroidx/appcompat/widget/AppCompatImageHelper;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 588: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 35739: Lcom/google/android/material/card/MaterialCardView;.setClipToOutline (Z)V
E/dalvikvm( 7455): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.google.android.material.card.MaterialCardViewHelper.createForegroundRippleDrawable
W/dalvikvm( 7455): VFY: unable to resolve new-instance 236 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/google/android/material/card/MaterialCardViewHelper;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1418: Landroid/graphics/drawable/InsetDrawable;.setDrawable (Landroid/graphics/drawable/Drawable;)V
E/dalvikvm( 7455): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.google.android.material.card.MaterialCardViewHelper.updateRippleColor
W/dalvikvm( 7455): VFY: unable to resolve check-cast 236 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/google/android/material/card/MaterialCardViewHelper;
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/graphics/Outline;)
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1115: Landroid/graphics/Outline;.setRoundRect (Landroid/graphics/Rect;F)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1166: Landroid/graphics/Path;.isConvex ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1166: Landroid/graphics/Path;.isConvex ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1048: Landroid/graphics/Color;.getModel ()Landroid/graphics/ColorSpace$Model;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1332: Landroid/graphics/drawable/Drawable;.applyTheme (Landroid/content/res/Resources$Theme;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1333: Landroid/graphics/drawable/Drawable;.canApplyTheme ()Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1344: Landroid/graphics/drawable/Drawable;.getColorFilter ()Landroid/graphics/ColorFilter;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1362: Landroid/graphics/drawable/Drawable;.inflate (Landroid/content/res/Resources;Lorg/xmlpull/v1/XmlPullParser;Landroid/util/AttributeSet;Landroid/content/res/Resources$Theme;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1384: Landroid/graphics/drawable/Drawable;.setHotspot (FF)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1385: Landroid/graphics/drawable/Drawable;.setHotspotBounds (IIII)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1386: Landroid/graphics/drawable/Drawable;.setLayoutDirection (I)Z
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1389: Landroid/graphics/drawable/Drawable;.setTint (I)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1390: Landroid/graphics/drawable/Drawable;.setTintList (Landroid/content/res/ColorStateList;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 1391: Landroid/graphics/drawable/Drawable;.setTintMode (Landroid/graphics/PorterDuff$Mode;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4415: Landroid/widget/TextView;.getAutoSizeMaxTextSize ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4416: Landroid/widget/TextView;.getAutoSizeMinTextSize ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4417: Landroid/widget/TextView;.getAutoSizeStepGranularity ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4418: Landroid/widget/TextView;.getAutoSizeTextAvailableSizes ()[I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4419: Landroid/widget/TextView;.getAutoSizeTextType ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4460: Landroid/widget/TextView;.getTextClassifier ()Landroid/view/textclassifier/TextClassifier;
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/textclassifier/TextClassifier;)
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/textclassifier/TextClassifier;)
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4487: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4488: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4489: Landroid/widget/TextView;.setAutoSizeTextTypeWithDefaults (I)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4505: Landroid/widget/TextView;.setFirstBaselineToTopHeight (I)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4512: Landroid/widget/TextView;.setLastBaselineToBottomHeight (I)V
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/textclassifier/TextClassifier;)
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4535: Landroid/widget/TextView;.setTextClassifier (Landroid/view/textclassifier/TextClassifier;)V
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/textclassifier/TextClassifier;)
W/dalvikvm( 7455): VFY: unable to resolve static method 1284: Landroid/graphics/Typeface;.create (Landroid/graphics/Typeface;IZ)Landroid/graphics/Typeface;
W/dalvikvm( 7455): VFY: unable to resolve static method 1284: Landroid/graphics/Typeface;.create (Landroid/graphics/Typeface;IZ)Landroid/graphics/Typeface;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4507: Landroid/widget/TextView;.setFontVariationSettings (Ljava/lang/String;)Z
W/dalvikvm( 7455): VFY: unable to resolve static method 1897: Landroid/os/LocaleList;.forLanguageTags (Ljava/lang/String;)Landroid/os/LocaleList;
W/dalvikvm( 7455): VFY: unable to resolve static method 57605: Ljava/util/Locale;.forLanguageTag (Ljava/lang/String;)Ljava/util/Locale;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4417: Landroid/widget/TextView;.getAutoSizeStepGranularity ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4507: Landroid/widget/TextView;.setFontVariationSettings (Ljava/lang/String;)Z
W/dalvikvm( 7455): VFY: unable to resolve static method 2212: Landroid/text/StaticLayout$Builder;.obtain (Ljava/lang/CharSequence;IILandroid/text/TextPaint;I)Landroid/text/StaticLayout$Builder;
W/dalvikvm( 7455): VFY: unable to resolve static method 1284: Landroid/graphics/Typeface;.create (Landroid/graphics/Typeface;IZ)Landroid/graphics/Typeface;
E/dalvikvm( 7455): Could not find class 'android.view.textclassifier.TextClassificationManager', referenced from method androidx.appcompat.widget.AppCompatTextClassifierHelper.getTextClassifier
W/dalvikvm( 7455): VFY: unable to resolve const-class 642 (Landroid/view/textclassifier/TextClassificationManager;) in Landroidx/appcompat/widget/AppCompatTextClassifierHelper;
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/textclassifier/TextClassifier;)
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/view/textclassifier/TextClassifier;)
W/dalvikvm( 7455): VFY: unable to resolve virtual method 7802: Landroidx/appcompat/widget/AppCompatButton;.setElevation (F)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3727: Landroid/widget/Button;.getAutoSizeMaxTextSize ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3728: Landroid/widget/Button;.getAutoSizeMinTextSize ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3729: Landroid/widget/Button;.getAutoSizeStepGranularity ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3730: Landroid/widget/Button;.getAutoSizeTextAvailableSizes ()[I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3731: Landroid/widget/Button;.getAutoSizeTextType ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3741: Landroid/widget/Button;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3742: Landroid/widget/Button;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 3743: Landroid/widget/Button;.setAutoSizeTextTypeWithDefaults (I)V
E/dalvikvm( 7455): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.google.android.material.button.MaterialButtonHelper.createBackground
W/dalvikvm( 7455): VFY: unable to resolve new-instance 236 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/google/android/material/button/MaterialButtonHelper;
E/dalvikvm( 7455): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.google.android.material.button.MaterialButtonHelper.setRippleColor
W/dalvikvm( 7455): VFY: unable to resolve instanceof 236 (Landroid/graphics/drawable/RippleDrawable;) in Lcom/google/android/material/button/MaterialButtonHelper;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4415: Landroid/widget/TextView;.getAutoSizeMaxTextSize ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4416: Landroid/widget/TextView;.getAutoSizeMinTextSize ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4417: Landroid/widget/TextView;.getAutoSizeStepGranularity ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4418: Landroid/widget/TextView;.getAutoSizeTextAvailableSizes ()[I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4419: Landroid/widget/TextView;.getAutoSizeTextType ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4422: Landroid/widget/TextView;.getCompoundDrawableTintList ()Landroid/content/res/ColorStateList;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4423: Landroid/widget/TextView;.getCompoundDrawableTintMode ()Landroid/graphics/PorterDuff$Mode;
W/dalvikvm( 7455): VFY: unable to resolve static method 1628: Landroid/icu/text/DecimalFormatSymbols;.getInstance (Ljava/util/Locale;)Landroid/icu/text/DecimalFormatSymbols;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4465: Landroid/widget/TextView;.getTextMetricsParams ()Landroid/text/PrecomputedText$Params;
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4421: Landroid/widget/TextView;.getBreakStrategy ()I
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4487: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4488: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4489: Landroid/widget/TextView;.setAutoSizeTextTypeWithDefaults (I)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4493: Landroid/widget/TextView;.setCompoundDrawableTintList (Landroid/content/res/ColorStateList;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4494: Landroid/widget/TextView;.setCompoundDrawableTintMode (Landroid/graphics/PorterDuff$Mode;)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4505: Landroid/widget/TextView;.setFirstBaselineToTopHeight (I)V
W/dalvikvm( 7455): VFY: unable to find class referenced in signature (Landroid/text/PrecomputedText;)
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4533: Landroid/widget/TextView;.setTextAppearance (I)V
W/dalvikvm( 7455): VFY: unable to resolve virtual method 4492: Landroid/widget/TextView;.setBreakStrategy (I)V
W/dalvikvm( 7455): VFY: unable to resolve static field 213 (SENSOR_INFO_PIXEL_ARRAY_SIZE) in Landroid/hardware/camera2/CameraCharacteristics;
W/dalvikvm( 7455): VFY: unable to resolve static field 270 (SUPPORTED_64_BIT_ABIS) in Landroid/os/Build;
E/MediaPlayerService( 1032): setDataSource(/system/media/audio/ui/camera_click.ogg)
E/MediaPlayerService( 1032): setDataSource(/system/media/audio/ui/VideoRecord.ogg)
E/V4L2Camera( 1032): ERROR opening V4L interface: No such file or directory
E/CameraHardware( 1032): Camera device /dev/video0 open failed.
E/V4L2Camera( 1032): Open: VIDIOC_TRY_FMT Failed: Bad file number
E/V4L2Camera( 1032): Open: VIDIOC_TRY_FMT Failed: Bad file number
E/V4L2Camera( 1032): Open: VIDIOC_TRY_FMT Failed: Bad file number
E/V4L2Camera( 1032): Open: VIDIOC_TRY_FMT Failed: Bad file number
E/V4L2Camera( 1032): Open: VIDIOC_TRY_FMT Failed: Bad file number
E/V4L2Camera( 1032): Open: VIDIOC_TRY_FMT Failed: Bad file number
E/V4L2Camera( 1032): Open: VIDIOC_TRY_FMT Failed: Bad file number
E/V4L2Camera( 1032): Open: VIDIOC_S_FMT Failed: Bad file number
E/CameraHardware( 1032): Camera setParameters failed: Bad file number
E/V4L2Camera( 1032): Init: VIDIOC_REQBUFS failed: Bad file number
E/CameraHardware( 1032): Camera Init failed: Bad file number
E/V4L2Camera( 1032): StartStreaming: Unable to start capture: Bad file number
E/CameraHardware( 1032): Camera StartStreaming failed: Bad file number
E/CameraHAL( 1032): camera Open Fail
E/CameraClient( 1032): Could not open camera 0: -12
E/CameraClient( 1032): initialize: Camera 0: unable to initialize device: Out of memory (-12)
W/AudioFlinger( 1032): session id 52 not found for pid 7455
W/AudioFlinger( 1032): session id 53 not found for pid 7455
W/CameraBase( 7455): An error occurred while connecting to camera: 0
W/dalvikvm( 7455): threadid=1: thread exiting with uncaught exception (group=0x41cf2ba8)
E/AndroidRuntime( 7455): FATAL EXCEPTION: main
E/AndroidRuntime( 7455): Process: com.octo4a, PID: 7455
E/AndroidRuntime( 7455): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.octo4a/com.octo4a.ui.InitialActivity}: java.lang.RuntimeException: Fail to connect to camera service
E/AndroidRuntime( 7455):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
E/AndroidRuntime( 7455):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
E/AndroidRuntime( 7455):        at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 7455):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 7455):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7455):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7455):        at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 7455):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7455):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7455):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:815)
E/AndroidRuntime( 7455):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:631)
E/AndroidRuntime( 7455):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 7455): Caused by: java.lang.RuntimeException: Fail to connect to camera service
E/AndroidRuntime( 7455):        at android.hardware.Camera.native_setup(Native Method)
E/AndroidRuntime( 7455):        at android.hardware.Camera.<init>(Camera.java:362)
E/AndroidRuntime( 7455):        at android.hardware.Camera.open(Camera.java:321)
E/AndroidRuntime( 7455):        at com.octo4a.camera.CameraEnumerationRepository.enumerateCameras(CameraEnumerationRepository.kt:86)
E/AndroidRuntime( 7455):        at com.octo4a.ui.InitialActivity.prepareBootstrap(InitialActivity.kt:72)
E/AndroidRuntime( 7455):        at com.octo4a.ui.InitialActivity.onCreate(InitialActivity.kt:68)
E/AndroidRuntime( 7455):        at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 7455):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 7455):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
E/AndroidRuntime( 7455):        ... 11 more
W/ActivityManager( 1578):   Force finishing activity com.octo4a/.ui.InitialActivity
W/WindowManager( 1578): Screenshot failure taking screenshot for (1280x720) to layer 21035
W/ContextImpl( 1578): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1163 com.android.server.am.AppErrorDialog.sendReportBrocast:193 com.android.server.am.AppErrorDialog.<init>:144 com.android.server.am.ActivityManagerService$2.handleMessage:1135 android.os.Handler.dispatchMessage:102
W/InputMethodManagerService( 1578): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42835808 attribute=null, token = android.os.BinderProxy@426e57a0

```

**Comment by alufers** [comment]
I think it should be fixed with the newer version.
